### ISSUE TITLE
Support for ARM64

### ISSUE THREAD

**Issue by SalvatorePreviti** [JoakimCh/tdewolff-minify#1]
This package currently does not support Darwin ARM64, but https://github.com/tdewolff/minify provides precompiled binaries for Darwin ARM64.

Would it be possible to update the version of the minifier and include support for ARM64?

Thank you very much.

➜  x npm i tdewolff-minify
npm ERR! code 1
npm ERR! path /Users/sp/my/x/node_modules/tdewolff-minify
npm ERR! command failed
npm ERR! command sh -c node source/minifyDownloader/downloadScript.js
npm ERR! Trying to download the native precompiled minify binary for your platform...
npm ERR! file:///Users/sp/my/x/node_modules/tdewolff-minify/source/minifyDownloader/minifyDownloader.js:220
npm ERR!       error("I couldn't find a release for your platform: "+wantedAsset)
npm ERR!       ^
npm ERR!
npm ERR! TypeError: error is not a function
npm ERR!     at getLatestRelease (file:///Users/sp/my/x/node_modules/tdewolff-minify/source/minifyDownloader/minifyDownloader.js:220:7)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm ERR!     at async file:///Users/sp/my/x/node_modules/tdewolff-minify/source/minifyDownloader/downloadScript.js:6:1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sp/.npm/_logs/2022-05-16T06_54_04_111Z-debug-0.log

![image](https://user-images.githubusercontent.com/6913178/168535823-a24c922e-fe1f-4ead-b109-76b78f71a7ad.png)

I am using Node 16,
  arch: 'arm64',
  platform: 'darwin',

**Comment by JoakimCh** [comment]
It's funny how my error function failed, I should fix that...

But I don't see any ARM64 precompiled binaries in his releases, only `minify_darwin_amd64.tar.gz`. I guess your eyes saw what they wanted to see or is it hidden somewhere else?

https://github.com/tdewolff/minify/releases/latest/checksums.txt

**Comment by SalvatorePreviti** [comment]
Yes you are right :( my eyes lied! Sorry about that.

I will ask tdewolff if he plans to release an arm64 - I know is currently problematic because github actions has no arm64 yet - https://github.com/actions/runner/issues/805
